name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the FileRise application code into `app/`
      - name: Checkout FileRise code
        uses: actions/checkout@v4
        with:
          repository: error311/FileRise
          token: ${{ secrets.GITHUB_TOKEN }}
          path: app

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # 5. Build & push, pointing at the FileRise context & Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./app                # ← build context is the FileRise code
          file: ./app/Dockerfile        # ← use the Dockerfile moved into FileRise
          push: true
          tags: error311/filerise-docker:latest
          cache-from: type=local,src=/tmp/.docker-cache
          cache-to: type=local,dest=/tmp/.docker-cache
          secrets: |
            id=git_token,src=${{ secrets.GIT_TOKEN }}