name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the FileRise application code into `app/`
      - name: Checkout FileRise code
        uses: actions/checkout@v4
        with:
          repository: error311/FileRise
          token: ${{ secrets.GITHUB_TOKEN }}
          path: app

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # Build & push, pointing at the FileRise context & Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./app                # ← build context is the FileRise code
          file: ./app/Dockerfile        # ← use the Dockerfile moved into FileRise
          push: true
          tags: |
            error311/filerise-docker:latest
            error311/filerise-docker:${{ github.run_number }}          
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false   # avoid registry hiccups
          sbom: false         # same
          secrets: |
            id=git_token,src=${{ secrets.GIT_TOKEN }}
