name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'
      - 'CHANGELOG.md'
      - '.github/workflows/main.yml'
      - 'Dockerfile'
      - 'app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 0) Checkout THIS repo (filerise-docker) so we can read VERSION
      - name: Checkout filerise-docker
        uses: actions/checkout@v4

      # 1) Read version (from VERSION written by FileRise workflow)
      - name: Read version
        id: ver
        run: |
          if [[ -f VERSION ]]; then
            V="$(tr -d '[:space:]' < VERSION)"
            if [[ -n "$V" ]]; then
              echo "version=$V" >> $GITHUB_OUTPUT
            else
              echo "VERSION file is empty"; exit 1
            fi
          else
            echo "VERSION file not found"; exit 1
          fi

      # 2) Checkout the FileRise application code into `app/`
      - name: Checkout FileRise code
        uses: actions/checkout@v4
        with:
          repository: error311/FileRise
          token: ${{ secrets.GITHUB_TOKEN }}
          path: app

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3) Build & push (context is the FileRise code)
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            error311/filerise-docker:latest
            error311/filerise-docker:${{ steps.ver.outputs.version }}
          labels: |
            org.opencontainers.image.title=FileRise
            org.opencontainers.image.version=${{ steps.ver.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
